// Writes src/version.ts from package.json so the version is a compile-time
// constant — works identically for the npm bundle and `bun build --compile`
// binaries (no runtime package.json lookup).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const out = `// Generated by scripts/sync-version.mjs — do not edit by hand.
export const VERSION = ${JSON.stringify(pkg.version)};
export const USER_AGENT = \`enconvert-cli/\${VERSION} (\${process.platform}; \${process.arch})\`;
`;
writeFileSync(join(root, "src", "version.ts"), out);
console.log(`src/version.ts <- ${pkg.version}`);
