# fish completion for enconvert.
# Generated by `enconvert completion fish`. Fully static: no network calls,
# no callbacks into the CLI. Regenerate after upgrading enconvert.

function __enconvert_known_path
    contains -- $argv[1] 'convert' 'data' 'compress' 'pdf' 'markdown' 'url' 'url pdf' 'url screenshot' 'url markdown' 'site' 'site pdf' 'site screenshot' 'perceive' 'perceive get' 'perceive batch' 'perceive batch get' 'perceive batch cancel' 'discover' 'lookup' 'distill' 'ingest' 'ingest create' 'ingest files' 'ingest list' 'ingest get' 'ingest cancel' 'ingest retry-webhook' 'ingest webhook-secret' 'ingest webhook-secret show' 'ingest webhook-secret rotate' 'jobs' 'jobs get' 'jobs batch' 'jobs wait' 'files' 'files download' 'formats' 'params' 'params convert' 'whoami' 'status' 'usage' 'version' 'docs' 'open' 'auth' 'auth login' 'auth logout' 'auth status' 'auth token' 'auth switch' 'config' 'config get' 'config set' 'config unset' 'config list' 'config edit' 'config path' 'config debug' 'api' 'completion' 'upgrade' 'mcp' 'mcp install' 'mcp uninstall' 'mcp list' 'help'
end

function __enconvert_path
    set -l tokens (commandline -opc)
    set -e tokens[1]
    set -l path ''
    set -l candidate ''
    for t in $tokens
        if string match -q -- '-*' $t
            continue
        end
        if test -z "$path"
            set candidate $t
        else
            set candidate "$path $t"
        end
        if __enconvert_known_path $candidate
            set path $candidate
        end
    end
    echo $path
end

function __enconvert_at
    test "$(__enconvert_path)" = "$argv[1]"
end

# enconvert
complete -c enconvert -f -n '__enconvert_at ""' -a convert -d 'convert local files; the endpoint is inferred from the extension and --to'
complete -c enconvert -f -n '__enconvert_at ""' -a data -d 'convert between data formats (the 11 data routes)'
complete -c enconvert -f -n '__enconvert_at ""' -a compress -d 'compress images (png, jpeg, webp); output keeps the input extension'
complete -c enconvert -f -n '__enconvert_at ""' -a pdf -d 'convert anything to PDF (anything-to-pdf)'
complete -c enconvert -f -n '__enconvert_at ""' -a markdown -d 'convert documents to Markdown (anything-to-markdown)'
complete -c enconvert -f -n '__enconvert_at ""' -a url -d 'render URLs to PDF, screenshots, or Markdown'
complete -c enconvert -f -n '__enconvert_at ""' -a site -d 'crawl a website and convert every discovered page (always async)'
complete -c enconvert -f -n '__enconvert_at ""' -a perceive -d 'Render one URL and capture outputs: markdown, HTML, screenshots, PDF, links...'
complete -c enconvert -f -n '__enconvert_at ""' -a discover -d 'Discover a site s URLs via sitemap and/or crawl (POST /v2/discover). URLs l...'
complete -c enconvert -f -n '__enconvert_at ""' -a lookup -d 'Web search, optionally perceiving and enriching the top results (POST /v2/l...'
complete -c enconvert -f -n '__enconvert_at ""' -a distill -d 'Extract structured data from pages using a schema, a prompt, or CSS selecto...'
complete -c enconvert -f -n '__enconvert_at ""' -a ingest -d 'Ingest web pages or files into chunked JSONL for RAG pipelines (/v2/ingest).'
complete -c enconvert -f -n '__enconvert_at ""' -a jobs -d 'inspect and wait on conversion jobs and batches'
complete -c enconvert -f -n '__enconvert_at ""' -a files -d 'work with stored conversion outputs'
complete -c enconvert -f -n '__enconvert_at ""' -a formats -d 'list every supported file conversion (offline; no API key needed)'
complete -c enconvert -f -n '__enconvert_at ""' -a params -d 'show accepted parameters for a conversion'
complete -c enconvert -f -n '__enconvert_at ""' -a whoami -d 'print the project and plan behind the active API key (GET /v1/whoami)'
complete -c enconvert -f -n '__enconvert_at ""' -a status -d 'gateway health plus an auth check; informational, always exits 0'
complete -c enconvert -f -n '__enconvert_at ""' -a usage -d 'plan and key details; usage counters live in the dashboard'
complete -c enconvert -f -n '__enconvert_at ""' -a version -d 'print the CLI version, platform, and install method'
complete -c enconvert -f -n '__enconvert_at ""' -a docs -d 'open the CLI docs (or a docs search) in your browser'
complete -c enconvert -f -n '__enconvert_at ""' -a open -d 'open the Enconvert dashboard, billing, or docs in your browser'
complete -c enconvert -f -n '__enconvert_at ""' -a auth -d 'authenticate the CLI with your Enconvert account'
complete -c enconvert -f -n '__enconvert_at ""' -a config -d 'read and write CLI configuration (user config file, per-profile)'
complete -c enconvert -f -n '__enconvert_at ""' -a api -d 'Send an authenticated request to any Enconvert gateway endpoint'
complete -c enconvert -f -n '__enconvert_at ""' -a completion -d 'Generate a shell completion script (bash, zsh, fish, powershell)'
complete -c enconvert -f -n '__enconvert_at ""' -a upgrade -d 'Upgrade the Enconvert CLI via the channel it was installed from'
complete -c enconvert -f -n '__enconvert_at ""' -a mcp -d 'Manage the Enconvert MCP server in AI tools (Claude, Cursor, Codex, ...)'
complete -c enconvert -f -n '__enconvert_at ""' -a help -d 'show help for a command, or a topic: exit-codes, environment, formatting'
complete -c enconvert -n '__enconvert_at ""' -l version -s V -d 'print the CLI version'
complete -c enconvert -n '__enconvert_at ""' -l verbose -s v -d 'diagnostics on stderr; repeatable (-vv)'
complete -c enconvert -n '__enconvert_at ""' -l debug -d 'stack traces and HTTP tracing (env ENCONVERT_DEBUG)'
complete -c enconvert -n '__enconvert_at ""' -l quiet -s q -d 'suppress non-essential stderr; errors still shown'
complete -c enconvert -n '__enconvert_at ""' -l json -d 'one JSON document on stdout (the gateway s raw response)'
complete -c enconvert -n '__enconvert_at ""' -l jsonl -d 'NDJSON stream on stdout'
complete -c enconvert -n '__enconvert_at ""' -l jq -r -d 'filter JSON output (bundled jq subset; no jq binary needed)'
complete -c enconvert -n '__enconvert_at ""' -l template -r -d 'format JSON output with a Go-style template'
complete -c enconvert -n '__enconvert_at ""' -l color -x -a 'auto always never' -d 'colourize output'
complete -c enconvert -n '__enconvert_at ""' -l no-color -d 'disable colour (same as --color never)'
complete -c enconvert -n '__enconvert_at ""' -l no-progress -d 'disable progress output'
complete -c enconvert -n '__enconvert_at ""' -l yes -s y -d 'assume yes for confirmation prompts'
complete -c enconvert -n '__enconvert_at ""' -l force -s F -d 'overwrite existing files / skip safety checks'
complete -c enconvert -n '__enconvert_at ""' -l skip-existing -d 'skip conversions whose output file already exists'
complete -c enconvert -n '__enconvert_at ""' -l dry-run -s n -d 'describe what would happen without executing or spending quota'
complete -c enconvert -n '__enconvert_at ""' -l no-input -d 'never prompt; fail (exit 2) if a required value is missing (env ENCONVERT_N...'
complete -c enconvert -n '__enconvert_at ""' -l config -r -d 'use this config file only (env ENCONVERT_CONFIG)'
complete -c enconvert -n '__enconvert_at ""' -l profile -s p -r -d 'config profile (env ENCONVERT_PROFILE)'
complete -c enconvert -n '__enconvert_at ""' -l api-key -r -d 'API key; @file reads a file, - reads stdin (env ENCONVERT_API_KEY)'
complete -c enconvert -n '__enconvert_at ""' -l api-url -r -d 'API base URL (env ENCONVERT_API_URL)'
complete -c enconvert -n '__enconvert_at ""' -l timeout -r -d 'per-HTTP-request timeout, e.g. 120s (NOT --wait-timeout)'
complete -c enconvert -n '__enconvert_at ""' -l retries -r -d 'retries for idempotent requests'
complete -c enconvert -n '__enconvert_at ""' -l concurrency -s j -r -d 'parallel operations for multi-input commands'
complete -c enconvert -n '__enconvert_at ""' -l help -s h -d 'show help'

# enconvert convert
complete -c enconvert -n '__enconvert_at "convert"' -l to -s t -x -a 'csv heic html jpeg json md pdf png svg toml webp xml yaml' -d 'target format (required unless --endpoint)'
complete -c enconvert -n '__enconvert_at "convert"' -l from -x -a 'bmp csv doc docx epub gif heic heif htm html jpeg jpg json markdown md mdown mkd numbers odp ods odt ots pages pdf png ppt pptx rtf svg text tif tiff toml txt webp xhtml xls xlsx xml yaml yml' -d 'override the input format sniffed from the extension'
complete -c enconvert -n '__enconvert_at "convert"' -l endpoint -x -a 'anything-to-markdown anything-to-pdf compress-image csv-to-json csv-to-xml doc-to-pdf excel-to-pdf heic-to-jpeg heic-to-png heic-to-svg heic-to-webp html-to-pdf jpeg-to-heic jpeg-to-png jpeg-to-svg jpeg-to-webp json-to-csv json-to-toml json-to-xml json-to-yaml markdown-to-html markdown-to-pdf numbers-to-pdf odp-to-pdf ods-to-pdf odt-to-pdf ots-to-pdf pages-to-pdf pdf-to-jpeg png-to-heic png-to-jpeg png-to-svg png-to-webp ppt-to-pdf svg-to-heic svg-to-jpeg svg-to-png svg-to-webp toml-to-json webp-to-heic webp-to-jpeg webp-to-png webp-to-svg xml-to-csv xml-to-json yaml-to-json' -d 'exact gateway route name, e.g. doc-to-pdf'
complete -c enconvert -n '__enconvert_at "convert"' -l output -s o -r -d 'output file, or "-" for bytes on stdout (single input only)'
complete -c enconvert -n '__enconvert_at "convert"' -l output-dir -s O -r -d 'output directory for multi-file results'
complete -c enconvert -n '__enconvert_at "convert"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "convert"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "convert"' -l job-id -r -d 'client-supplied job id (crash-recovery handle; single input only)'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-page-size -r -d 'page size: A0-A6, B0-B5, Letter, Legal, Tabloid, Ledger'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-orientation -x -a 'portrait landscape' -d 'page orientation'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-margin -r -d 'margins in mm, e.g. 20,15,20,15'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-scale -r -d 'render scale 0.1-2.0'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-grayscale -d 'convert the output PDF to grayscale'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-header -r -d 'header HTML (@file reads from disk)'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-footer -r -d 'footer HTML (@file reads from disk)'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-header-height -r -d 'header height in mm'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-footer-height -r -d 'footer height in mm'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-page-width -r -d 'custom page width in mm (use with --pdf-page-height)'
complete -c enconvert -n '__enconvert_at "convert"' -l pdf-page-height -r -d 'custom page height in mm'
complete -c enconvert -n '__enconvert_at "convert"' -l width -r -d 'output width (svg-to-jpeg/png/webp only)'
complete -c enconvert -n '__enconvert_at "convert"' -l height -r -d 'output height (svg-to-jpeg/png/webp only)'
complete -c enconvert -n '__enconvert_at "convert"' -l target-size-kb -r -d 'target size in KB (compress-image only)'
complete -c enconvert -n '__enconvert_at "convert"' -l help -s h -d 'show help'

# enconvert data
complete -c enconvert -n '__enconvert_at "data"' -l to -s t -x -a 'csv heic html jpeg json md pdf png svg toml webp xml yaml' -d 'target data format'
complete -c enconvert -n '__enconvert_at "data"' -l output -s o -r -d 'output file, or "-" for bytes on stdout (single input only)'
complete -c enconvert -n '__enconvert_at "data"' -l output-dir -s O -r -d 'output directory for multi-file results'
complete -c enconvert -n '__enconvert_at "data"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "data"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "data"' -l job-id -r -d 'client-supplied job id (crash-recovery handle; single input only)'
complete -c enconvert -n '__enconvert_at "data"' -l help -s h -d 'show help'

# enconvert compress
complete -c enconvert -n '__enconvert_at "compress"' -l target-size-kb -r -d 'target size in KB (>= 1)'
complete -c enconvert -n '__enconvert_at "compress"' -l output -s o -r -d 'output file, or "-" for bytes on stdout (single input only)'
complete -c enconvert -n '__enconvert_at "compress"' -l output-dir -s O -r -d 'output directory for multi-file results'
complete -c enconvert -n '__enconvert_at "compress"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "compress"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "compress"' -l job-id -r -d 'client-supplied job id (crash-recovery handle; single input only)'
complete -c enconvert -n '__enconvert_at "compress"' -l help -s h -d 'show help'

# enconvert pdf
complete -c enconvert -n '__enconvert_at "pdf"' -l output -s o -r -d 'output file, or "-" for bytes on stdout (single input only)'
complete -c enconvert -n '__enconvert_at "pdf"' -l output-dir -s O -r -d 'output directory for multi-file results'
complete -c enconvert -n '__enconvert_at "pdf"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "pdf"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "pdf"' -l job-id -r -d 'client-supplied job id (crash-recovery handle; single input only)'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-page-size -r -d 'page size: A0-A6, B0-B5, Letter, Legal, Tabloid, Ledger'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-orientation -x -a 'portrait landscape' -d 'page orientation'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-margin -r -d 'margins in mm, e.g. 20,15,20,15'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-scale -r -d 'render scale 0.1-2.0'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-grayscale -d 'convert the output PDF to grayscale'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-header -r -d 'header HTML (@file reads from disk)'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-footer -r -d 'footer HTML (@file reads from disk)'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-header-height -r -d 'header height in mm'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-footer-height -r -d 'footer height in mm'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-page-width -r -d 'custom page width in mm (use with --pdf-page-height)'
complete -c enconvert -n '__enconvert_at "pdf"' -l pdf-page-height -r -d 'custom page height in mm'
complete -c enconvert -n '__enconvert_at "pdf"' -l help -s h -d 'show help'

# enconvert markdown
complete -c enconvert -n '__enconvert_at "markdown"' -l output -s o -r -d 'output file, or "-" for bytes on stdout (single input only)'
complete -c enconvert -n '__enconvert_at "markdown"' -l output-dir -s O -r -d 'output directory for multi-file results'
complete -c enconvert -n '__enconvert_at "markdown"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "markdown"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "markdown"' -l job-id -r -d 'client-supplied job id (crash-recovery handle; single input only)'
complete -c enconvert -n '__enconvert_at "markdown"' -l help -s h -d 'show help'

# enconvert url
complete -c enconvert -f -n '__enconvert_at "url"' -a pdf -d 'render web pages to PDF'
complete -c enconvert -f -n '__enconvert_at "url"' -a screenshot -d 'capture full-page screenshots (PNG)'
complete -c enconvert -f -n '__enconvert_at "url"' -a markdown -d 'extract web pages as Markdown'
complete -c enconvert -n '__enconvert_at "url"' -l help -s h -d 'show help'

# enconvert url pdf
complete -c enconvert -n '__enconvert_at "url pdf"' -l output -s o -r -d 'output file, or "-" for bytes on stdout (single URL only)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l output-dir -s O -r -d 'output directory for multi-URL results'
complete -c enconvert -n '__enconvert_at "url pdf"' -l viewport-width -r -d 'viewport width (gateway default 1920)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l viewport-height -r -d 'viewport height (gateway default 1080)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l wait-for-selector -r -d 'wait for a CSS selector before capturing'
complete -c enconvert -n '__enconvert_at "url pdf"' -l wait-for-selector-timeout -r -d 'selector wait budget in ms (max 60000)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l load-media -d 'load images and media (gateway default)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l no-load-media -d 'skip images and media'
complete -c enconvert -n '__enconvert_at "url pdf"' -l enable-scroll -d 'scroll the page to trigger lazy loading (gateway default)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l no-enable-scroll -d 'do not scroll the page'
complete -c enconvert -n '__enconvert_at "url pdf"' -l sticky-header -d 'neutralize sticky headers (gateway default; maps handle_sticky_header)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l no-sticky-header -d 'leave sticky headers alone'
complete -c enconvert -n '__enconvert_at "url pdf"' -l handle-cookies -d 'auto-dismiss cookie banners (gateway default)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l no-handle-cookies -d 'leave cookie banners alone'
complete -c enconvert -n '__enconvert_at "url pdf"' -l wait-for-images -d 'wait for images to finish loading (gateway default)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l no-wait-for-images -d 'do not wait for images'
complete -c enconvert -n '__enconvert_at "url pdf"' -l block-ads -d 'block ad network requests'
complete -c enconvert -n '__enconvert_at "url pdf"' -l block-media -d 'block heavy media requests'
complete -c enconvert -n '__enconvert_at "url pdf"' -l basic-auth -r -d 'HTTP basic auth for the target site'
complete -c enconvert -n '__enconvert_at "url pdf"' -l cookie -r -d 'cookie name=value;domain=... (repeatable)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l header -r -d 'extra request header Name: value (repeatable)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l notification-email -r -d 'completion email (private keys)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l callback-url -r -d 'completion webhook URL (plan-gated)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l job-id -r -d 'client-supplied job id (crash-recovery handle)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l async -d 'queue the render and return a batch id (202)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l no-async -d 'force a synchronous render'
complete -c enconvert -n '__enconvert_at "url pdf"' -l zip -d 'bundle multiple URLs into a single ZIP'
complete -c enconvert -n '__enconvert_at "url pdf"' -l single-page -d 'render as one tall page (gateway default)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l no-single-page -d 'paginate the output'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-page-size -r -d 'page size: A0-A6, B0-B5, Letter, Legal, Tabloid, Ledger'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-orientation -x -a 'portrait landscape' -d 'page orientation'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-margin -r -d 'margins in mm, e.g. 20,15,20,15'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-scale -r -d 'render scale 0.1-2.0'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-grayscale -d 'convert the output PDF to grayscale'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-header -r -d 'header HTML (@file reads from disk)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-footer -r -d 'footer HTML (@file reads from disk)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-header-height -r -d 'header height in mm'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-footer-height -r -d 'footer height in mm'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-page-width -r -d 'custom page width in mm (use with --pdf-page-height)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l pdf-page-height -r -d 'custom page height in mm'
complete -c enconvert -n '__enconvert_at "url pdf"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "url pdf"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "url pdf"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "url pdf"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "url pdf"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "url pdf"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "url pdf"' -l help -s h -d 'show help'

# enconvert url screenshot
complete -c enconvert -n '__enconvert_at "url screenshot"' -l output -s o -r -d 'output file, or "-" for bytes on stdout (single URL only)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l output-dir -s O -r -d 'output directory for multi-URL results'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l viewport-width -r -d 'viewport width (gateway default 1920)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l viewport-height -r -d 'viewport height (gateway default 1080)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l wait-for-selector -r -d 'wait for a CSS selector before capturing'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l wait-for-selector-timeout -r -d 'selector wait budget in ms (max 60000)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l load-media -d 'load images and media (gateway default)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l no-load-media -d 'skip images and media'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l enable-scroll -d 'scroll the page to trigger lazy loading (gateway default)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l no-enable-scroll -d 'do not scroll the page'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l sticky-header -d 'neutralize sticky headers (gateway default; maps handle_sticky_header)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l no-sticky-header -d 'leave sticky headers alone'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l handle-cookies -d 'auto-dismiss cookie banners (gateway default)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l no-handle-cookies -d 'leave cookie banners alone'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l wait-for-images -d 'wait for images to finish loading (gateway default)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l no-wait-for-images -d 'do not wait for images'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l block-ads -d 'block ad network requests'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l block-media -d 'block heavy media requests'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l basic-auth -r -d 'HTTP basic auth for the target site'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l cookie -r -d 'cookie name=value;domain=... (repeatable)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l header -r -d 'extra request header Name: value (repeatable)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l notification-email -r -d 'completion email (private keys)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l callback-url -r -d 'completion webhook URL (plan-gated)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l job-id -r -d 'client-supplied job id (crash-recovery handle)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l async -d 'queue the render and return a batch id (202)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l no-async -d 'force a synchronous render'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l zip -d 'bundle multiple URLs into a single ZIP'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "url screenshot"' -l help -s h -d 'show help'

# enconvert url markdown
complete -c enconvert -n '__enconvert_at "url markdown"' -l output -s o -r -d 'output file, or "-" for bytes on stdout (single URL only)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l output-dir -s O -r -d 'output directory for multi-URL results'
complete -c enconvert -n '__enconvert_at "url markdown"' -l viewport-width -r -d 'viewport width (gateway default 1920)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l viewport-height -r -d 'viewport height (gateway default 1080)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l wait-for-selector -r -d 'wait for a CSS selector before capturing'
complete -c enconvert -n '__enconvert_at "url markdown"' -l wait-for-selector-timeout -r -d 'selector wait budget in ms (max 60000)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l load-media -d 'load images and media (gateway default)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l no-load-media -d 'skip images and media'
complete -c enconvert -n '__enconvert_at "url markdown"' -l enable-scroll -d 'scroll the page to trigger lazy loading (gateway default)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l no-enable-scroll -d 'do not scroll the page'
complete -c enconvert -n '__enconvert_at "url markdown"' -l sticky-header -d 'neutralize sticky headers (gateway default; maps handle_sticky_header)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l no-sticky-header -d 'leave sticky headers alone'
complete -c enconvert -n '__enconvert_at "url markdown"' -l handle-cookies -d 'auto-dismiss cookie banners (gateway default)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l no-handle-cookies -d 'leave cookie banners alone'
complete -c enconvert -n '__enconvert_at "url markdown"' -l wait-for-images -d 'wait for images to finish loading (gateway default)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l no-wait-for-images -d 'do not wait for images'
complete -c enconvert -n '__enconvert_at "url markdown"' -l block-ads -d 'block ad network requests'
complete -c enconvert -n '__enconvert_at "url markdown"' -l block-media -d 'block heavy media requests'
complete -c enconvert -n '__enconvert_at "url markdown"' -l basic-auth -r -d 'HTTP basic auth for the target site'
complete -c enconvert -n '__enconvert_at "url markdown"' -l cookie -r -d 'cookie name=value;domain=... (repeatable)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l header -r -d 'extra request header Name: value (repeatable)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l notification-email -r -d 'completion email (private keys)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l callback-url -r -d 'completion webhook URL (plan-gated)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l job-id -r -d 'client-supplied job id (crash-recovery handle)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l async -d 'queue the render and return a batch id (202)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l no-async -d 'force a synchronous render'
complete -c enconvert -n '__enconvert_at "url markdown"' -l zip -d 'bundle multiple URLs into a single ZIP'
complete -c enconvert -n '__enconvert_at "url markdown"' -l single-page -d 'render as one tall page (gateway default)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l no-single-page -d 'paginate the output'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-page-size -r -d 'page size: A0-A6, B0-B5, Letter, Legal, Tabloid, Ledger'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-orientation -x -a 'portrait landscape' -d 'page orientation'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-margin -r -d 'margins in mm, e.g. 20,15,20,15'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-scale -r -d 'render scale 0.1-2.0'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-grayscale -d 'convert the output PDF to grayscale'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-header -r -d 'header HTML (@file reads from disk)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-footer -r -d 'footer HTML (@file reads from disk)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-header-height -r -d 'header height in mm'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-footer-height -r -d 'footer height in mm'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-page-width -r -d 'custom page width in mm (use with --pdf-page-height)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l pdf-page-height -r -d 'custom page height in mm'
complete -c enconvert -n '__enconvert_at "url markdown"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "url markdown"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "url markdown"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "url markdown"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "url markdown"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "url markdown"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "url markdown"' -l help -s h -d 'show help'

# enconvert site
complete -c enconvert -f -n '__enconvert_at "site"' -a pdf -d 'crawl a site and render every page to PDF (ZIP result)'
complete -c enconvert -f -n '__enconvert_at "site"' -a screenshot -d 'crawl a site and screenshot every page (ZIP result)'
complete -c enconvert -n '__enconvert_at "site"' -l help -s h -d 'show help'

# enconvert site pdf
complete -c enconvert -n '__enconvert_at "site pdf"' -l crawl-mode -x -a 'auto sitemap full' -d 'page discovery strategy (plan-gated)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l include-pattern -r -d 'include URLs matching this regex (full crawl only; repeatable)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l exclude-pattern -r -d 'exclude URLs matching this regex (full crawl only; repeatable)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l output -s o -r -d 'output path for the result ZIP'
complete -c enconvert -n '__enconvert_at "site pdf"' -l output-dir -s O -r -d 'output directory'
complete -c enconvert -n '__enconvert_at "site pdf"' -l viewport-width -r -d 'viewport width (gateway default 1920)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l viewport-height -r -d 'viewport height (gateway default 1080)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l wait-for-selector -r -d 'wait for a CSS selector before capturing'
complete -c enconvert -n '__enconvert_at "site pdf"' -l wait-for-selector-timeout -r -d 'selector wait budget in ms (max 60000)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l load-media -d 'load images and media (gateway default)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l no-load-media -d 'skip images and media'
complete -c enconvert -n '__enconvert_at "site pdf"' -l enable-scroll -d 'scroll the page to trigger lazy loading (gateway default)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l no-enable-scroll -d 'do not scroll the page'
complete -c enconvert -n '__enconvert_at "site pdf"' -l sticky-header -d 'neutralize sticky headers (gateway default; maps handle_sticky_header)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l no-sticky-header -d 'leave sticky headers alone'
complete -c enconvert -n '__enconvert_at "site pdf"' -l handle-cookies -d 'auto-dismiss cookie banners (gateway default)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l no-handle-cookies -d 'leave cookie banners alone'
complete -c enconvert -n '__enconvert_at "site pdf"' -l wait-for-images -d 'wait for images to finish loading (gateway default)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l no-wait-for-images -d 'do not wait for images'
complete -c enconvert -n '__enconvert_at "site pdf"' -l block-ads -d 'block ad network requests'
complete -c enconvert -n '__enconvert_at "site pdf"' -l block-media -d 'block heavy media requests'
complete -c enconvert -n '__enconvert_at "site pdf"' -l basic-auth -r -d 'HTTP basic auth for the target site'
complete -c enconvert -n '__enconvert_at "site pdf"' -l cookie -r -d 'cookie name=value;domain=... (repeatable)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l header -r -d 'extra request header Name: value (repeatable)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l notification-email -r -d 'completion email (private keys)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l callback-url -r -d 'completion webhook URL (plan-gated)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l job-id -r -d 'client-supplied job id (crash-recovery handle)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "site pdf"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "site pdf"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "site pdf"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "site pdf"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "site pdf"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "site pdf"' -l help -s h -d 'show help'

# enconvert site screenshot
complete -c enconvert -n '__enconvert_at "site screenshot"' -l crawl-mode -x -a 'auto sitemap full' -d 'page discovery strategy (plan-gated)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l include-pattern -r -d 'include URLs matching this regex (full crawl only; repeatable)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l exclude-pattern -r -d 'exclude URLs matching this regex (full crawl only; repeatable)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l output -s o -r -d 'output path for the result ZIP'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l output-dir -s O -r -d 'output directory'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l viewport-width -r -d 'viewport width (gateway default 1920)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l viewport-height -r -d 'viewport height (gateway default 1080)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l wait-for-selector -r -d 'wait for a CSS selector before capturing'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l wait-for-selector-timeout -r -d 'selector wait budget in ms (max 60000)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l load-media -d 'load images and media (gateway default)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l no-load-media -d 'skip images and media'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l enable-scroll -d 'scroll the page to trigger lazy loading (gateway default)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l no-enable-scroll -d 'do not scroll the page'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l sticky-header -d 'neutralize sticky headers (gateway default; maps handle_sticky_header)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l no-sticky-header -d 'leave sticky headers alone'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l handle-cookies -d 'auto-dismiss cookie banners (gateway default)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l no-handle-cookies -d 'leave cookie banners alone'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l wait-for-images -d 'wait for images to finish loading (gateway default)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l no-wait-for-images -d 'do not wait for images'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l block-ads -d 'block ad network requests'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l block-media -d 'block heavy media requests'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l basic-auth -r -d 'HTTP basic auth for the target site'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l cookie -r -d 'cookie name=value;domain=... (repeatable)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l header -r -d 'extra request header Name: value (repeatable)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l notification-email -r -d 'completion email (private keys)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l callback-url -r -d 'completion webhook URL (plan-gated)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l output-filename -r -d 'server-side output filename (a timestamp is always appended)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l job-id -r -d 'client-supplied job id (crash-recovery handle)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "site screenshot"' -l help -s h -d 'show help'

# enconvert perceive
complete -c enconvert -f -n '__enconvert_at "perceive"' -a get -d 'Fetch a previous perceive operation with freshly signed URLs (GET /v2/perce...'
complete -c enconvert -f -n '__enconvert_at "perceive"' -a batch -d 'Perceive up to 1000 URLs in one job (POST /v2/perceive/batch; finishes inli...'
complete -c enconvert -n '__enconvert_at "perceive"' -l output-dir -s O -r -d 'download every produced artifact into this directory'
complete -c enconvert -n '__enconvert_at "perceive"' -l output-file -s o -r -d 'direct download: write the artifact to this path ( - streams bytes to stdout)'
complete -c enconvert -n '__enconvert_at "perceive"' -l url-only -d 'print only the presigned artifact URLs'
complete -c enconvert -n '__enconvert_at "perceive"' -l direct-download -d 'stream the artifact s bytes as the response body (needs exactly one --output)'
complete -c enconvert -n '__enconvert_at "perceive"' -l output -r -d 'comma-separated outputs: markdown, html_cleaned, html_raw, screenshot, scre...'
complete -c enconvert -n '__enconvert_at "perceive"' -l extract -r -d 'comma-separated extractors: tables, prices, contacts, metadata, main_conten...'
complete -c enconvert -n '__enconvert_at "perceive"' -l schema-file -r -d 'JSON Schema file for structured extraction (sent as `schema`)'
complete -c enconvert -n '__enconvert_at "perceive"' -l wait-for -r -d 'wait for a CSS selector, css:<sel>, or js:<expr> before capture (max 1024 c...'
complete -c enconvert -n '__enconvert_at "perceive"' -l wait-timeout-ms -r -d 'budget for --wait-for in ms, 0-60000 (server default: 30000)'
complete -c enconvert -n '__enconvert_at "perceive"' -l js-code -r -d 'JavaScript to run on the page before capture; @file reads a file (max 20000...'
complete -c enconvert -n '__enconvert_at "perceive"' -l viewport -r -d 'viewport size, e.g. 1440x900 (width 320-3840, height 240-2160)'
complete -c enconvert -n '__enconvert_at "perceive"' -l mobile -d 'emulate a mobile device'
complete -c enconvert -n '__enconvert_at "perceive"' -l respect-robots -d 'honour robots.txt'
complete -c enconvert -n '__enconvert_at "perceive"' -l full-page -d 'keep the full page content including navigation and site chrome (server def...'
complete -c enconvert -n '__enconvert_at "perceive"' -l cache-mode -x -a 'enabled bypass refresh' -d 'render cache behaviour (server default: enabled)'
complete -c enconvert -n '__enconvert_at "perceive"' -l block-resource -r -d 'comma-separated resource types to block: image, media, font, stylesheet, sc...'
complete -c enconvert -n '__enconvert_at "perceive"' -l header -r -d 'extra request header Name: value (repeatable, max 20)'
complete -c enconvert -n '__enconvert_at "perceive"' -l cookie -r -d 'cookie name=value;domain=… or name=value;url=… (repeatable, max 50)'
complete -c enconvert -n '__enconvert_at "perceive"' -l basic-auth -r -d 'HTTP basic auth credentials'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-page-size -r -d 'PDF page size: A0-A6, B0-B5, Letter, Legal, Tabloid, Ledger (default A4)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-orientation -x -a 'portrait landscape' -d 'PDF orientation (default portrait)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-margin -r -d 'PDF margins in mm; one value or top,right,bottom,left (default 10)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-scale -r -d 'PDF render scale 0.1-2.0 (default 1.0)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-grayscale -d 'grayscale PDF output'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-header -r -d 'PDF header HTML (max 2000 chars)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-footer -r -d 'PDF footer HTML (max 2000 chars)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-header-height -r -d 'PDF header height in mm (server default: 15)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-footer-height -r -d 'PDF footer height in mm (server default: 15)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-page-width -r -d 'custom PDF page width in mm (use with --pdf-page-height)'
complete -c enconvert -n '__enconvert_at "perceive"' -l pdf-page-height -r -d 'custom PDF page height in mm'
complete -c enconvert -n '__enconvert_at "perceive"' -l help -s h -d 'show help'

# enconvert perceive get
complete -c enconvert -n '__enconvert_at "perceive get"' -l output-dir -s O -r -d 'download every artifact into this directory'
complete -c enconvert -n '__enconvert_at "perceive get"' -l url-only -d 'print only the presigned artifact URLs'
complete -c enconvert -n '__enconvert_at "perceive get"' -l help -s h -d 'show help'

# enconvert perceive batch
complete -c enconvert -f -n '__enconvert_at "perceive batch"' -a get -d 'Fetch a perceive batch s status and artifacts (GET /v2/perceive/batch/{job_...'
complete -c enconvert -f -n '__enconvert_at "perceive batch"' -a cancel -d 'Cancel a perceive batch; completed URLs keep their artifacts (DELETE /v2/pe...'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l input-file -r -d 'read URLs from a file: one per line, # comments allowed'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l output-mode -x -a 'manifest zip' -d 'artifact packaging (server default: manifest)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l output-file -s o -r -d 'zip mode: download the archive to this path ( - streams bytes to stdout)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l output-dir -s O -r -d 'zip mode: download the archive into this directory'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l output -r -d 'comma-separated outputs: markdown, html_cleaned, html_raw, screenshot, scre...'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l extract -r -d 'comma-separated extractors: tables, prices, contacts, metadata, main_conten...'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l schema-file -r -d 'JSON Schema file for structured extraction (sent as `schema`)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l wait-for -r -d 'wait for a CSS selector, css:<sel>, or js:<expr> before capture (max 1024 c...'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l wait-timeout-ms -r -d 'budget for --wait-for in ms, 0-60000 (server default: 30000)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l js-code -r -d 'JavaScript to run on the page before capture; @file reads a file (max 20000...'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l viewport -r -d 'viewport size, e.g. 1440x900 (width 320-3840, height 240-2160)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l mobile -d 'emulate a mobile device'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l respect-robots -d 'honour robots.txt'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l full-page -d 'keep the full page content including navigation and site chrome (server def...'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l cache-mode -x -a 'enabled bypass refresh' -d 'render cache behaviour (server default: enabled)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l block-resource -r -d 'comma-separated resource types to block: image, media, font, stylesheet, sc...'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l header -r -d 'extra request header Name: value (repeatable, max 20)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l cookie -r -d 'cookie name=value;domain=… or name=value;url=… (repeatable, max 50)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l basic-auth -r -d 'HTTP basic auth credentials'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-page-size -r -d 'PDF page size: A0-A6, B0-B5, Letter, Legal, Tabloid, Ledger (default A4)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-orientation -x -a 'portrait landscape' -d 'PDF orientation (default portrait)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-margin -r -d 'PDF margins in mm; one value or top,right,bottom,left (default 10)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-scale -r -d 'PDF render scale 0.1-2.0 (default 1.0)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-grayscale -d 'grayscale PDF output'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-header -r -d 'PDF header HTML (max 2000 chars)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-footer -r -d 'PDF footer HTML (max 2000 chars)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-header-height -r -d 'PDF header height in mm (server default: 15)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-footer-height -r -d 'PDF footer height in mm (server default: 15)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-page-width -r -d 'custom PDF page width in mm (use with --pdf-page-height)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l pdf-page-height -r -d 'custom PDF page height in mm'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "perceive batch"' -l help -s h -d 'show help'

# enconvert perceive batch get
complete -c enconvert -n '__enconvert_at "perceive batch get"' -l output-file -s o -r -d 'zip mode: download the archive to this path ( - streams bytes to stdout)'
complete -c enconvert -n '__enconvert_at "perceive batch get"' -l output-dir -s O -r -d 'zip mode: download the archive into this directory'
complete -c enconvert -n '__enconvert_at "perceive batch get"' -l url-only -d 'print URLs only; never download'
complete -c enconvert -n '__enconvert_at "perceive batch get"' -l help -s h -d 'show help'

# enconvert perceive batch cancel
complete -c enconvert -n '__enconvert_at "perceive batch cancel"' -l help -s h -d 'show help'

# enconvert discover
complete -c enconvert -n '__enconvert_at "discover"' -l mode -x -a 'sitemap crawl hybrid' -d 'discovery strategy (server default: hybrid)'
complete -c enconvert -n '__enconvert_at "discover"' -l max-urls -r -d 'maximum URLs to return, 1-1000 (server default: 100)'
complete -c enconvert -n '__enconvert_at "discover"' -l max-depth -r -d 'crawl depth, 1-5 (server default: 2)'
complete -c enconvert -n '__enconvert_at "discover"' -l include-pattern -r -d 'keep only URLs matching this regex (repeatable, max 50)'
complete -c enconvert -n '__enconvert_at "discover"' -l exclude-pattern -r -d 'drop URLs matching this regex, applied after includes (repeatable, max 50)'
complete -c enconvert -n '__enconvert_at "discover"' -l same-domain-only -d 'restrict results to the seed domain (server default)'
complete -c enconvert -n '__enconvert_at "discover"' -l no-same-domain-only -d 'allow URLs on other domains'
complete -c enconvert -n '__enconvert_at "discover"' -l respect-robots -d 'filter out URLs disallowed by robots.txt'
complete -c enconvert -n '__enconvert_at "discover"' -l render-js -x -a 'auto never always' -d 'JS rendering during crawl (server default: auto)'
complete -c enconvert -n '__enconvert_at "discover"' -l help -s h -d 'show help'

# enconvert lookup
complete -c enconvert -n '__enconvert_at "lookup"' -l category -x -a 'web news images scholar patents maps' -d 'search vertical (server default: web)'
complete -c enconvert -n '__enconvert_at "lookup"' -l country -r -d 'country bias, Google gl code (max 8 chars)'
complete -c enconvert -n '__enconvert_at "lookup"' -l locale -r -d 'interface locale, Google hl code (max 16 chars)'
complete -c enconvert -n '__enconvert_at "lookup"' -l time-filter -x -a 'hour day week month year' -d 'restrict results by age'
complete -c enconvert -n '__enconvert_at "lookup"' -l num-results -r -d 'results per page, 1-100 (server default: 10)'
complete -c enconvert -n '__enconvert_at "lookup"' -l page -r -d 'result page, 1-10 (server default: 1)'
complete -c enconvert -n '__enconvert_at "lookup"' -l location -r -d 'location bias, e.g. Austin, Texas (max 128 chars)'
complete -c enconvert -n '__enconvert_at "lookup"' -l no-autocorrect -d 'disable query autocorrection'
complete -c enconvert -n '__enconvert_at "lookup"' -l perceive-top -r -d 'perceive the top N results, 0-10 (each consumes one perceive operation)'
complete -c enconvert -n '__enconvert_at "lookup"' -l enrich-output -r -d 'outputs for perceived results: markdown, html_cleaned, html_raw, screenshot...'
complete -c enconvert -n '__enconvert_at "lookup"' -l enrich-concurrency -r -d 'parallel enrich fetches, 1-5 (server default: 3)'
complete -c enconvert -n '__enconvert_at "lookup"' -l enrich-schema-file -r -d 'JSON Schema (or flat field:description map) for structured enrich extraction'
complete -c enconvert -n '__enconvert_at "lookup"' -l synthesize-answer -d 'synthesize an LLM answer with citations across enriched results'
complete -c enconvert -n '__enconvert_at "lookup"' -l answer-prompt -r -d 'custom instruction for the synthesized answer (max 1000 chars)'
complete -c enconvert -n '__enconvert_at "lookup"' -l help -s h -d 'show help'

# enconvert distill
complete -c enconvert -n '__enconvert_at "distill"' -l discover-from -r -d 'discover pages from this seed instead of listing URLs'
complete -c enconvert -n '__enconvert_at "distill"' -l discover-mode -x -a 'sitemap crawl hybrid' -d 'discovery strategy for --discover-from (server default: hybrid)'
complete -c enconvert -n '__enconvert_at "distill"' -l discover-max-pages -r -d 'max discovered pages to distill, 1-50 (server default: 10)'
complete -c enconvert -n '__enconvert_at "distill"' -l schema-file -r -d 'JSON Schema (or flat field:description map) describing the fields to extract'
complete -c enconvert -n '__enconvert_at "distill"' -l prompt -r -d 'natural-language description of what to extract (max 2000 chars; a schema i...'
complete -c enconvert -n '__enconvert_at "distill"' -l css-schema-file -r -d 'CSS extraction schema file: {baseSelector, fields[]} (sent as css_schema)'
complete -c enconvert -n '__enconvert_at "distill"' -l wait-for -r -d 'wait for a CSS selector, css:<sel>, or js:<expr> before capture (max 1024 c...'
complete -c enconvert -n '__enconvert_at "distill"' -l wait-timeout-ms -r -d 'budget for --wait-for in ms, 0-60000 (server default: 30000)'
complete -c enconvert -n '__enconvert_at "distill"' -l header -r -d 'extra request header Name: value (repeatable, max 20)'
complete -c enconvert -n '__enconvert_at "distill"' -l cookie -r -d 'cookie name=value;domain=… or name=value;url=… (repeatable, max 50)'
complete -c enconvert -n '__enconvert_at "distill"' -l respect-robots -d 'honour robots.txt'
complete -c enconvert -n '__enconvert_at "distill"' -l help -s h -d 'show help'

# enconvert ingest
complete -c enconvert -f -n '__enconvert_at "ingest"' -a create -d 'Create an ingest job from explicit URLs, a sitemap, or a crawl (POST /v2/in...'
complete -c enconvert -f -n '__enconvert_at "ingest"' -a files -d 'Ingest local files, 1-200 per job (POST /v2/ingest/files, multipart, 202).'
complete -c enconvert -f -n '__enconvert_at "ingest"' -a list -d 'List this project s ingest jobs, newest first (GET /v2/ingest).'
complete -c enconvert -f -n '__enconvert_at "ingest"' -a get -d 'Show one ingest job, including its output URL and webhook state (GET /v2/in...'
complete -c enconvert -f -n '__enconvert_at "ingest"' -a cancel -d 'Cancel an ingest job; terminal jobs are returned unchanged (DELETE /v2/inge...'
complete -c enconvert -f -n '__enconvert_at "ingest"' -a retry-webhook -d 'Re-deliver the completion webhook for a completed job (POST /v2/ingest/{ing...'
complete -c enconvert -f -n '__enconvert_at "ingest"' -a webhook-secret -d 'Show or rotate the per-project webhook signing secret.'
complete -c enconvert -n '__enconvert_at "ingest"' -l help -s h -d 'show help'

# enconvert ingest create
complete -c enconvert -n '__enconvert_at "ingest create"' -l url-file -r -d 'read URLs from a file: one per line, # comments allowed'
complete -c enconvert -n '__enconvert_at "ingest create"' -l mode -x -a 'urls sitemap crawl' -d 'urls (default) takes a URL list; sitemap/crawl take exactly one seed URL'
complete -c enconvert -n '__enconvert_at "ingest create"' -l max-pages -r -d 'discovery cap for sitemap/crawl, 1-1000 (server default: 50)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l max-depth -r -d 'crawl depth, 1-5 (server default: 2)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l include-pattern -r -d 'keep only URLs matching this regex (repeatable, max 50)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l exclude-pattern -r -d 'drop URLs matching this regex (repeatable, max 50)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l same-domain-only -d 'restrict discovery to the seed domain (server default)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l no-same-domain-only -d 'allow other domains during discovery'
complete -c enconvert -n '__enconvert_at "ingest create"' -l respect-robots -d 'honour robots.txt'
complete -c enconvert -n '__enconvert_at "ingest create"' -l wait-for -r -d 'wait for a CSS selector, css:<sel>, or js:<expr> on each page (max 1024 chars)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l wait-timeout-ms -r -d 'budget for --wait-for in ms, 0-60000 (server default: 30000)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l chunk-max-words -r -d 'words per chunk, 32-4000 (server default: 512)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l chunk-sentence-overlap -r -d 'sentences of overlap between chunks, 0-10 (server default: 1)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l webhook-url -r -d 'webhook called on completion (signed; see `enconvert ingest webhook-secret ...'
complete -c enconvert -n '__enconvert_at "ingest create"' -l output -s o -r -d 'download the completed JSONL to this path ( - streams to stdout)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "ingest create"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "ingest create"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "ingest create"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "ingest create"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "ingest create"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "ingest create"' -l help -s h -d 'show help'

# enconvert ingest files
complete -c enconvert -n '__enconvert_at "ingest files"' -l max-words -r -d 'words per chunk, 32-4000 (server default: 512)'
complete -c enconvert -n '__enconvert_at "ingest files"' -l sentence-overlap -r -d 'sentences of overlap between chunks, 0-10 (server default: 1)'
complete -c enconvert -n '__enconvert_at "ingest files"' -l webhook-url -r -d 'webhook called on completion (signed; see `enconvert ingest webhook-secret ...'
complete -c enconvert -n '__enconvert_at "ingest files"' -l output -s o -r -d 'download the completed JSONL to this path ( - streams to stdout)'
complete -c enconvert -n '__enconvert_at "ingest files"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "ingest files"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "ingest files"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "ingest files"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "ingest files"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "ingest files"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "ingest files"' -l help -s h -d 'show help'

# enconvert ingest list
complete -c enconvert -n '__enconvert_at "ingest list"' -l skip -r -d 'rows to skip (server default: 0)'
complete -c enconvert -n '__enconvert_at "ingest list"' -l limit -r -d 'rows to return, 1-100 (server default: 20)'
complete -c enconvert -n '__enconvert_at "ingest list"' -l help -s h -d 'show help'

# enconvert ingest get
complete -c enconvert -n '__enconvert_at "ingest get"' -l help -s h -d 'show help'

# enconvert ingest cancel
complete -c enconvert -n '__enconvert_at "ingest cancel"' -l help -s h -d 'show help'

# enconvert ingest retry-webhook
complete -c enconvert -n '__enconvert_at "ingest retry-webhook"' -l help -s h -d 'show help'

# enconvert ingest webhook-secret
complete -c enconvert -f -n '__enconvert_at "ingest webhook-secret"' -a show -d 'Print the webhook signing secret (GET /v2/ingest/webhook-secret). Secret on...'
complete -c enconvert -f -n '__enconvert_at "ingest webhook-secret"' -a rotate -d 'Rotate the webhook signing secret (POST /v2/ingest/webhook-secret/rotate). ...'
complete -c enconvert -n '__enconvert_at "ingest webhook-secret"' -l help -s h -d 'show help'

# enconvert ingest webhook-secret show
complete -c enconvert -n '__enconvert_at "ingest webhook-secret show"' -l help -s h -d 'show help'

# enconvert ingest webhook-secret rotate
complete -c enconvert -n '__enconvert_at "ingest webhook-secret rotate"' -l help -s h -d 'show help'

# enconvert jobs
complete -c enconvert -f -n '__enconvert_at "jobs"' -a get -d 'fetch a v1 conversion job s status (GET /v1/convert/status/{id})'
complete -c enconvert -f -n '__enconvert_at "jobs"' -a batch -d 'fetch a v1 batch s status and per-item results (GET /v1/convert/batch/{id})'
complete -c enconvert -f -n '__enconvert_at "jobs"' -a wait -d 'block until a job or batch finishes (auto-detects ing_/per_/batch_/v1 ids)'
complete -c enconvert -n '__enconvert_at "jobs"' -l help -s h -d 'show help'

# enconvert jobs get
complete -c enconvert -n '__enconvert_at "jobs get"' -l help -s h -d 'show help'

# enconvert jobs batch
complete -c enconvert -n '__enconvert_at "jobs batch"' -l help -s h -d 'show help'

# enconvert jobs wait
complete -c enconvert -n '__enconvert_at "jobs wait"' -l wait -d 'wait for the job to finish'
complete -c enconvert -n '__enconvert_at "jobs wait"' -l no-wait -d 'print the job id and exit 0'
complete -c enconvert -n '__enconvert_at "jobs wait"' -l poll-interval -r -d 'seconds between polls'
complete -c enconvert -n '__enconvert_at "jobs wait"' -l wait-timeout -r -d 'how long to block on a queued job (default 15m)'
complete -c enconvert -n '__enconvert_at "jobs wait"' -l exit-status -d 'exit 9 when the job itself failed'
complete -c enconvert -n '__enconvert_at "jobs wait"' -l url-only -d 'print the presigned URL, skip the download'
complete -c enconvert -n '__enconvert_at "jobs wait"' -l help -s h -d 'show help'

# enconvert files
complete -c enconvert -f -n '__enconvert_at "files"' -a download -d 'download a stored object s bytes (GET /v1/convert/download/{key})'
complete -c enconvert -n '__enconvert_at "files"' -l help -s h -d 'show help'

# enconvert files download
complete -c enconvert -n '__enconvert_at "files download"' -l output -s o -r -d 'output file, or "-" for bytes on stdout'
complete -c enconvert -n '__enconvert_at "files download"' -l help -s h -d 'show help'

# enconvert formats
complete -c enconvert -n '__enconvert_at "formats"' -l from -x -a 'bmp csv doc docx epub gif heic heif htm html jpeg jpg json markdown md mdown mkd numbers odp ods odt ots pages pdf png ppt pptx rtf svg text tif tiff toml txt webp xhtml xls xlsx xml yaml yml' -d 'only conversions accepting this input format'
complete -c enconvert -n '__enconvert_at "formats"' -l to -x -a 'csv heic html jpeg json md pdf png svg toml webp xml yaml' -d 'only conversions producing this format'
complete -c enconvert -n '__enconvert_at "formats"' -l help -s h -d 'show help'

# enconvert params
complete -c enconvert -f -n '__enconvert_at "params"' -a convert -d 'parameters for one (from, to) conversion pair (offline)'
complete -c enconvert -n '__enconvert_at "params"' -l help -s h -d 'show help'

# enconvert params convert
complete -c enconvert -n '__enconvert_at "params convert"' -l from -x -a 'bmp csv doc docx epub gif heic heif htm html jpeg jpg json markdown md mdown mkd numbers odp ods odt ots pages pdf png ppt pptx rtf svg text tif tiff toml txt webp xhtml xls xlsx xml yaml yml' -d 'input format'
complete -c enconvert -n '__enconvert_at "params convert"' -l to -x -a 'csv heic html jpeg json md pdf png svg toml webp xml yaml' -d 'target format'
complete -c enconvert -n '__enconvert_at "params convert"' -l help -s h -d 'show help'

# enconvert whoami
complete -c enconvert -n '__enconvert_at "whoami"' -l help -s h -d 'show help'

# enconvert status
complete -c enconvert -n '__enconvert_at "status"' -l help -s h -d 'show help'

# enconvert usage
complete -c enconvert -n '__enconvert_at "usage"' -l help -s h -d 'show help'

# enconvert version
complete -c enconvert -n '__enconvert_at "version"' -l help -s h -d 'show help'

# enconvert docs
complete -c enconvert -n '__enconvert_at "docs"' -l help -s h -d 'show help'

# enconvert open
complete -c enconvert -f -n '__enconvert_at "open"' -a 'dashboard billing docs'
complete -c enconvert -n '__enconvert_at "open"' -l help -s h -d 'show help'

# enconvert auth
complete -c enconvert -f -n '__enconvert_at "auth"' -a login -d 'save an API key for the active profile (validated via GET /v1/whoami)'
complete -c enconvert -f -n '__enconvert_at "auth"' -a logout -d 'delete the stored API key for the active profile'
complete -c enconvert -f -n '__enconvert_at "auth"' -a status -d 'show which credential is in use and verify it against the gateway'
complete -c enconvert -f -n '__enconvert_at "auth"' -a token -d 'print the resolved API key on stdout (for scripts; nothing else is printed)'
complete -c enconvert -f -n '__enconvert_at "auth"' -a switch -d 'set default_profile in the user config'
complete -c enconvert -n '__enconvert_at "auth"' -l help -s h -d 'show help'

# enconvert auth login
complete -c enconvert -n '__enconvert_at "auth login"' -l with-token -d 'read the API key from stdin (CI-safe; never argv)'
complete -c enconvert -n '__enconvert_at "auth login"' -l help -s h -d 'show help'

# enconvert auth logout
complete -c enconvert -n '__enconvert_at "auth logout"' -l help -s h -d 'show help'

# enconvert auth status
complete -c enconvert -n '__enconvert_at "auth status"' -l help -s h -d 'show help'

# enconvert auth token
complete -c enconvert -n '__enconvert_at "auth token"' -l help -s h -d 'show help'

# enconvert auth switch
complete -c enconvert -n '__enconvert_at "auth switch"' -l help -s h -d 'show help'

# enconvert config
complete -c enconvert -f -n '__enconvert_at "config"' -a get -d 'print the resolved value of a setting'
complete -c enconvert -f -n '__enconvert_at "config"' -a set -d 'write a setting to the user config file (profile keys go under the active p...'
complete -c enconvert -f -n '__enconvert_at "config"' -a unset -d 'remove a setting from the user config file'
complete -c enconvert -f -n '__enconvert_at "config"' -a list -d 'print every resolved setting for the active profile'
complete -c enconvert -f -n '__enconvert_at "config"' -a edit -d 'open the user config file in $EDITOR (fallback vi)'
complete -c enconvert -f -n '__enconvert_at "config"' -a path -d 'print the user config file path'
complete -c enconvert -f -n '__enconvert_at "config"' -a debug -d 'print every setting with its value AND where it came from (the support comm...'
complete -c enconvert -n '__enconvert_at "config"' -l help -s h -d 'show help'

# enconvert config get
complete -c enconvert -n '__enconvert_at "config get"' -l help -s h -d 'show help'

# enconvert config set
complete -c enconvert -n '__enconvert_at "config set"' -l help -s h -d 'show help'

# enconvert config unset
complete -c enconvert -n '__enconvert_at "config unset"' -l help -s h -d 'show help'

# enconvert config list
complete -c enconvert -n '__enconvert_at "config list"' -l help -s h -d 'show help'

# enconvert config edit
complete -c enconvert -n '__enconvert_at "config edit"' -l help -s h -d 'show help'

# enconvert config path
complete -c enconvert -n '__enconvert_at "config path"' -l help -s h -d 'show help'

# enconvert config debug
complete -c enconvert -n '__enconvert_at "config debug"' -l help -s h -d 'show help'

# enconvert api
complete -c enconvert -n '__enconvert_at "api"' -l method -s X -r -d 'HTTP method (default GET; auto-POST when a field flag or --input is present)'
complete -c enconvert -n '__enconvert_at "api"' -l raw-field -s f -r -d 'string field; repeatable (shadows the global -F/--force here)'
complete -c enconvert -n '__enconvert_at "api"' -l field -s F -r -d 'typed field: true/false/null and integers become JSON, @file reads a file, ...'
complete -c enconvert -n '__enconvert_at "api"' -l header -s H -r -d 'request header Name: value ; repeatable'
complete -c enconvert -n '__enconvert_at "api"' -l input -r -d 'JSON request body from a file, or - for stdin (field flags then become quer...'
complete -c enconvert -n '__enconvert_at "api"' -l jq -s q -r -d 'filter the JSON response (shadows the global -q/--quiet here)'
complete -c enconvert -n '__enconvert_at "api"' -l template -s t -r -d 'format the JSON response with a template (shadows the global --template)'
complete -c enconvert -n '__enconvert_at "api"' -l include -s i -d 'print the HTTP status and response headers before the body'
complete -c enconvert -n '__enconvert_at "api"' -l silent -d 'do not print the response body'
complete -c enconvert -n '__enconvert_at "api"' -l paginate -d 'follow skip/limit pagination while the response reports has_more (GET only)'
complete -c enconvert -n '__enconvert_at "api"' -l slurp -d 'with --paginate, wrap all pages in one JSON array'
complete -c enconvert -n '__enconvert_at "api"' -l list-endpoints -d 'list every gateway endpoint from the bundled API index (offline)'
complete -c enconvert -n '__enconvert_at "api"' -l search -r -d 'search endpoints by path, summary, or tag (offline)'
complete -c enconvert -n '__enconvert_at "api"' -l describe -r -d 'show an endpoint s methods, params, and body fields (offline)'
complete -c enconvert -n '__enconvert_at "api"' -l help -s h -d 'show help'

# enconvert completion
complete -c enconvert -f -n '__enconvert_at "completion"' -a 'bash zsh fish powershell install'
complete -c enconvert -n '__enconvert_at "completion"' -l help -s h -d 'show help'

# enconvert upgrade
complete -c enconvert -n '__enconvert_at "upgrade"' -l help -s h -d 'show help'

# enconvert mcp
complete -c enconvert -f -n '__enconvert_at "mcp"' -a install -d 'Add the Enconvert MCP server to an AI client s config'
complete -c enconvert -f -n '__enconvert_at "mcp"' -a uninstall -d 'Remove the Enconvert MCP server entry from an AI client s config'
complete -c enconvert -f -n '__enconvert_at "mcp"' -a list -d 'Show MCP install status for every supported AI client'
complete -c enconvert -n '__enconvert_at "mcp"' -l help -s h -d 'show help'

# enconvert mcp install
complete -c enconvert -f -n '__enconvert_at "mcp install"' -a 'claude claude-code claude-desktop cursor codex windsurf vscode zed gemini gemini-cli opencode'
complete -c enconvert -n '__enconvert_at "mcp install"' -l help -s h -d 'show help'

# enconvert mcp uninstall
complete -c enconvert -f -n '__enconvert_at "mcp uninstall"' -a 'claude claude-code claude-desktop cursor codex windsurf vscode zed gemini gemini-cli opencode'
complete -c enconvert -n '__enconvert_at "mcp uninstall"' -l help -s h -d 'show help'

# enconvert mcp list
complete -c enconvert -n '__enconvert_at "mcp list"' -l help -s h -d 'show help'

# enconvert help
complete -c enconvert -n '__enconvert_at "help"' -l help -s h -d 'show help'

