# bash completion for enconvert                            -*- shell-script -*-
# Generated by `enconvert completion bash`. Fully static: no network calls,
# no callbacks into the CLI. Regenerate after upgrading enconvert.

_enconvert_known_path() {
  case "$1" in
    "convert"|"data"|"compress"|"pdf"|"markdown"|"url"|"url pdf"|"url screenshot"|"url markdown"|"site"|"site pdf"|"site screenshot"|"perceive"|"perceive get"|"perceive batch"|"perceive batch get"|"perceive batch cancel"|"discover"|"lookup"|"distill"|"ingest"|"ingest create"|"ingest files"|"ingest list"|"ingest get"|"ingest cancel"|"ingest retry-webhook"|"ingest webhook-secret"|"ingest webhook-secret show"|"ingest webhook-secret rotate"|"jobs"|"jobs get"|"jobs batch"|"jobs wait"|"files"|"files download"|"formats"|"params"|"params convert"|"whoami"|"status"|"usage"|"version"|"docs"|"open"|"auth"|"auth login"|"auth logout"|"auth status"|"auth token"|"auth switch"|"config"|"config get"|"config set"|"config unset"|"config list"|"config edit"|"config path"|"config debug"|"api"|"completion"|"upgrade"|"mcp"|"mcp install"|"mcp uninstall"|"mcp list"|"help") return 0 ;;
  esac
  return 1
}

_enconvert() {
  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  # Resolve the subcommand path, skipping flags (and, implicitly, flag
  # values and positionals: only known subcommand names extend the path).
  local path="" candidate="" w="" i
  for ((i = 1; i < COMP_CWORD; i++)); do
    w="${COMP_WORDS[i]}"
    case "$w" in -*) continue ;; esac
    if [ -z "$path" ]; then candidate="$w"; else candidate="$path $w"; fi
    if _enconvert_known_path "$candidate"; then path="$candidate"; fi
  done

  # Value suggestions for the flag before the cursor.
  case "$path|$prev" in
    "|--color")
      COMPREPLY=( $(compgen -W "auto always never" -- "$cur") )
      return ;;
    "convert|--to"|"convert|-t")
      COMPREPLY=( $(compgen -W "csv heic html jpeg json md pdf png svg toml webp xml yaml" -- "$cur") )
      return ;;
    "convert|--from")
      COMPREPLY=( $(compgen -W "bmp csv doc docx epub gif heic heif htm html jpeg jpg json markdown md mdown mkd numbers odp ods odt ots pages pdf png ppt pptx rtf svg text tif tiff toml txt webp xhtml xls xlsx xml yaml yml" -- "$cur") )
      return ;;
    "convert|--endpoint")
      COMPREPLY=( $(compgen -W "anything-to-markdown anything-to-pdf compress-image csv-to-json csv-to-xml doc-to-pdf excel-to-pdf heic-to-jpeg heic-to-png heic-to-svg heic-to-webp html-to-pdf jpeg-to-heic jpeg-to-png jpeg-to-svg jpeg-to-webp json-to-csv json-to-toml json-to-xml json-to-yaml markdown-to-html markdown-to-pdf numbers-to-pdf odp-to-pdf ods-to-pdf odt-to-pdf ots-to-pdf pages-to-pdf pdf-to-jpeg png-to-heic png-to-jpeg png-to-svg png-to-webp ppt-to-pdf svg-to-heic svg-to-jpeg svg-to-png svg-to-webp toml-to-json webp-to-heic webp-to-jpeg webp-to-png webp-to-svg xml-to-csv xml-to-json yaml-to-json" -- "$cur") )
      return ;;
    "convert|--pdf-orientation")
      COMPREPLY=( $(compgen -W "portrait landscape" -- "$cur") )
      return ;;
    "data|--to"|"data|-t")
      COMPREPLY=( $(compgen -W "csv heic html jpeg json md pdf png svg toml webp xml yaml" -- "$cur") )
      return ;;
    "pdf|--pdf-orientation")
      COMPREPLY=( $(compgen -W "portrait landscape" -- "$cur") )
      return ;;
    "url pdf|--pdf-orientation")
      COMPREPLY=( $(compgen -W "portrait landscape" -- "$cur") )
      return ;;
    "url markdown|--pdf-orientation")
      COMPREPLY=( $(compgen -W "portrait landscape" -- "$cur") )
      return ;;
    "site pdf|--crawl-mode")
      COMPREPLY=( $(compgen -W "auto sitemap full" -- "$cur") )
      return ;;
    "site screenshot|--crawl-mode")
      COMPREPLY=( $(compgen -W "auto sitemap full" -- "$cur") )
      return ;;
    "perceive|--cache-mode")
      COMPREPLY=( $(compgen -W "enabled bypass refresh" -- "$cur") )
      return ;;
    "perceive|--pdf-orientation")
      COMPREPLY=( $(compgen -W "portrait landscape" -- "$cur") )
      return ;;
    "perceive batch|--output-mode")
      COMPREPLY=( $(compgen -W "manifest zip" -- "$cur") )
      return ;;
    "perceive batch|--cache-mode")
      COMPREPLY=( $(compgen -W "enabled bypass refresh" -- "$cur") )
      return ;;
    "perceive batch|--pdf-orientation")
      COMPREPLY=( $(compgen -W "portrait landscape" -- "$cur") )
      return ;;
    "discover|--mode")
      COMPREPLY=( $(compgen -W "sitemap crawl hybrid" -- "$cur") )
      return ;;
    "discover|--render-js")
      COMPREPLY=( $(compgen -W "auto never always" -- "$cur") )
      return ;;
    "lookup|--category")
      COMPREPLY=( $(compgen -W "web news images scholar patents maps" -- "$cur") )
      return ;;
    "lookup|--time-filter")
      COMPREPLY=( $(compgen -W "hour day week month year" -- "$cur") )
      return ;;
    "distill|--discover-mode")
      COMPREPLY=( $(compgen -W "sitemap crawl hybrid" -- "$cur") )
      return ;;
    "ingest create|--mode")
      COMPREPLY=( $(compgen -W "urls sitemap crawl" -- "$cur") )
      return ;;
    "formats|--from")
      COMPREPLY=( $(compgen -W "bmp csv doc docx epub gif heic heif htm html jpeg jpg json markdown md mdown mkd numbers odp ods odt ots pages pdf png ppt pptx rtf svg text tif tiff toml txt webp xhtml xls xlsx xml yaml yml" -- "$cur") )
      return ;;
    "formats|--to")
      COMPREPLY=( $(compgen -W "csv heic html jpeg json md pdf png svg toml webp xml yaml" -- "$cur") )
      return ;;
    "params convert|--from")
      COMPREPLY=( $(compgen -W "bmp csv doc docx epub gif heic heif htm html jpeg jpg json markdown md mdown mkd numbers odp ods odt ots pages pdf png ppt pptx rtf svg text tif tiff toml txt webp xhtml xls xlsx xml yaml yml" -- "$cur") )
      return ;;
    "params convert|--to")
      COMPREPLY=( $(compgen -W "csv heic html jpeg json md pdf png svg toml webp xml yaml" -- "$cur") )
      return ;;
  esac

  local subs="" flags=""
  case "$path" in
    "")
      subs="convert data compress pdf markdown url site perceive discover lookup distill ingest jobs files formats params whoami status usage version docs open auth config api completion upgrade mcp help"
      flags="--version -V --verbose -v --debug --quiet -q --json --jsonl --jq --template --color --no-color --no-progress --yes -y --force -F --skip-existing --dry-run -n --no-input --config --profile -p --api-key --api-url --timeout --retries --concurrency -j --help -h"
      ;;
    "convert")
      subs=""
      flags="--to -t --from --endpoint --output -o --output-dir -O --url-only --output-filename --job-id --pdf-page-size --pdf-orientation --pdf-margin --pdf-scale --pdf-grayscale --pdf-header --pdf-footer --pdf-header-height --pdf-footer-height --pdf-page-width --pdf-page-height --width --height --target-size-kb --help -h"
      ;;
    "data")
      subs=""
      flags="--to -t --output -o --output-dir -O --url-only --output-filename --job-id --help -h"
      ;;
    "compress")
      subs=""
      flags="--target-size-kb --output -o --output-dir -O --url-only --output-filename --job-id --help -h"
      ;;
    "pdf")
      subs=""
      flags="--output -o --output-dir -O --url-only --output-filename --job-id --pdf-page-size --pdf-orientation --pdf-margin --pdf-scale --pdf-grayscale --pdf-header --pdf-footer --pdf-header-height --pdf-footer-height --pdf-page-width --pdf-page-height --help -h"
      ;;
    "markdown")
      subs=""
      flags="--output -o --output-dir -O --url-only --output-filename --job-id --help -h"
      ;;
    "url")
      subs="pdf screenshot markdown"
      flags="--help -h"
      ;;
    "url pdf")
      subs=""
      flags="--output -o --output-dir -O --viewport-width --viewport-height --wait-for-selector --wait-for-selector-timeout --load-media --no-load-media --enable-scroll --no-enable-scroll --sticky-header --no-sticky-header --handle-cookies --no-handle-cookies --wait-for-images --no-wait-for-images --block-ads --block-media --basic-auth --cookie --header --notification-email --callback-url --output-filename --job-id --async --no-async --zip --single-page --no-single-page --pdf-page-size --pdf-orientation --pdf-margin --pdf-scale --pdf-grayscale --pdf-header --pdf-footer --pdf-header-height --pdf-footer-height --pdf-page-width --pdf-page-height --wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "url screenshot")
      subs=""
      flags="--output -o --output-dir -O --viewport-width --viewport-height --wait-for-selector --wait-for-selector-timeout --load-media --no-load-media --enable-scroll --no-enable-scroll --sticky-header --no-sticky-header --handle-cookies --no-handle-cookies --wait-for-images --no-wait-for-images --block-ads --block-media --basic-auth --cookie --header --notification-email --callback-url --output-filename --job-id --async --no-async --zip --wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "url markdown")
      subs=""
      flags="--output -o --output-dir -O --viewport-width --viewport-height --wait-for-selector --wait-for-selector-timeout --load-media --no-load-media --enable-scroll --no-enable-scroll --sticky-header --no-sticky-header --handle-cookies --no-handle-cookies --wait-for-images --no-wait-for-images --block-ads --block-media --basic-auth --cookie --header --notification-email --callback-url --output-filename --job-id --async --no-async --zip --single-page --no-single-page --pdf-page-size --pdf-orientation --pdf-margin --pdf-scale --pdf-grayscale --pdf-header --pdf-footer --pdf-header-height --pdf-footer-height --pdf-page-width --pdf-page-height --wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "site")
      subs="pdf screenshot"
      flags="--help -h"
      ;;
    "site pdf")
      subs=""
      flags="--crawl-mode --include-pattern --exclude-pattern --output -o --output-dir -O --viewport-width --viewport-height --wait-for-selector --wait-for-selector-timeout --load-media --no-load-media --enable-scroll --no-enable-scroll --sticky-header --no-sticky-header --handle-cookies --no-handle-cookies --wait-for-images --no-wait-for-images --block-ads --block-media --basic-auth --cookie --header --notification-email --callback-url --output-filename --job-id --wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "site screenshot")
      subs=""
      flags="--crawl-mode --include-pattern --exclude-pattern --output -o --output-dir -O --viewport-width --viewport-height --wait-for-selector --wait-for-selector-timeout --load-media --no-load-media --enable-scroll --no-enable-scroll --sticky-header --no-sticky-header --handle-cookies --no-handle-cookies --wait-for-images --no-wait-for-images --block-ads --block-media --basic-auth --cookie --header --notification-email --callback-url --output-filename --job-id --wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "perceive")
      subs="get batch"
      flags="--output-dir -O --url-only --output --extract --schema-file --wait-for --wait-timeout-ms --js-code --viewport --mobile --respect-robots --cache-mode --block-resource --header --cookie --basic-auth --pdf-page-size --pdf-orientation --pdf-margin --pdf-scale --pdf-grayscale --pdf-header --pdf-footer --pdf-header-height --pdf-footer-height --pdf-page-width --pdf-page-height --help -h"
      ;;
    "perceive get")
      subs=""
      flags="--output-dir -O --url-only --help -h"
      ;;
    "perceive batch")
      subs="get cancel"
      flags="--input-file --output-mode --output-file -o --output-dir -O --output --extract --schema-file --wait-for --wait-timeout-ms --js-code --viewport --mobile --respect-robots --cache-mode --block-resource --header --cookie --basic-auth --pdf-page-size --pdf-orientation --pdf-margin --pdf-scale --pdf-grayscale --pdf-header --pdf-footer --pdf-header-height --pdf-footer-height --pdf-page-width --pdf-page-height --wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "perceive batch get")
      subs=""
      flags="--output-file -o --output-dir -O --url-only --help -h"
      ;;
    "perceive batch cancel")
      subs=""
      flags="--help -h"
      ;;
    "discover")
      subs=""
      flags="--mode --max-urls --max-depth --include-pattern --exclude-pattern --same-domain-only --no-same-domain-only --respect-robots --render-js --help -h"
      ;;
    "lookup")
      subs=""
      flags="--category --country --locale --time-filter --num-results --page --location --no-autocorrect --perceive-top --enrich-output --enrich-concurrency --enrich-schema-file --synthesize-answer --answer-prompt --help -h"
      ;;
    "distill")
      subs=""
      flags="--discover-from --discover-mode --discover-max-pages --schema-file --prompt --css-schema-file --wait-for --wait-timeout-ms --header --cookie --respect-robots --help -h"
      ;;
    "ingest")
      subs="create files list get cancel retry-webhook webhook-secret"
      flags="--help -h"
      ;;
    "ingest create")
      subs=""
      flags="--url-file --mode --max-pages --max-depth --include-pattern --exclude-pattern --same-domain-only --no-same-domain-only --respect-robots --wait-for --wait-timeout-ms --chunk-max-words --chunk-sentence-overlap --webhook-url --output -o --wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "ingest files")
      subs=""
      flags="--max-words --sentence-overlap --webhook-url --output -o --wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "ingest list")
      subs=""
      flags="--skip --limit --help -h"
      ;;
    "ingest get")
      subs=""
      flags="--help -h"
      ;;
    "ingest cancel")
      subs=""
      flags="--help -h"
      ;;
    "ingest retry-webhook")
      subs=""
      flags="--help -h"
      ;;
    "ingest webhook-secret")
      subs="show rotate"
      flags="--help -h"
      ;;
    "ingest webhook-secret show")
      subs=""
      flags="--help -h"
      ;;
    "ingest webhook-secret rotate")
      subs=""
      flags="--help -h"
      ;;
    "jobs")
      subs="get batch wait"
      flags="--help -h"
      ;;
    "jobs get")
      subs=""
      flags="--help -h"
      ;;
    "jobs batch")
      subs=""
      flags="--help -h"
      ;;
    "jobs wait")
      subs=""
      flags="--wait --no-wait --poll-interval --wait-timeout --exit-status --url-only --help -h"
      ;;
    "files")
      subs="download"
      flags="--help -h"
      ;;
    "files download")
      subs=""
      flags="--output -o --help -h"
      ;;
    "formats")
      subs=""
      flags="--from --to --help -h"
      ;;
    "params")
      subs="convert"
      flags="--help -h"
      ;;
    "params convert")
      subs=""
      flags="--from --to --help -h"
      ;;
    "whoami")
      subs=""
      flags="--help -h"
      ;;
    "status")
      subs=""
      flags="--help -h"
      ;;
    "usage")
      subs=""
      flags="--help -h"
      ;;
    "version")
      subs=""
      flags="--help -h"
      ;;
    "docs")
      subs=""
      flags="--help -h"
      ;;
    "open")
      subs="dashboard billing docs"
      flags="--help -h"
      ;;
    "auth")
      subs="login logout status token switch"
      flags="--help -h"
      ;;
    "auth login")
      subs=""
      flags="--with-token --help -h"
      ;;
    "auth logout")
      subs=""
      flags="--help -h"
      ;;
    "auth status")
      subs=""
      flags="--help -h"
      ;;
    "auth token")
      subs=""
      flags="--help -h"
      ;;
    "auth switch")
      subs=""
      flags="--help -h"
      ;;
    "config")
      subs="get set unset list edit path debug"
      flags="--help -h"
      ;;
    "config get")
      subs=""
      flags="--help -h"
      ;;
    "config set")
      subs=""
      flags="--help -h"
      ;;
    "config unset")
      subs=""
      flags="--help -h"
      ;;
    "config list")
      subs=""
      flags="--help -h"
      ;;
    "config edit")
      subs=""
      flags="--help -h"
      ;;
    "config path")
      subs=""
      flags="--help -h"
      ;;
    "config debug")
      subs=""
      flags="--help -h"
      ;;
    "api")
      subs=""
      flags="--method -X --raw-field -f --field -F --header -H --input --jq -q --template -t --include -i --silent --paginate --slurp --list-endpoints --search --describe --help -h"
      ;;
    "completion")
      subs="bash zsh fish powershell install"
      flags="--help -h"
      ;;
    "upgrade")
      subs=""
      flags="--help -h"
      ;;
    "mcp")
      subs="install uninstall list"
      flags="--help -h"
      ;;
    "mcp install")
      subs="claude claude-code claude-desktop cursor codex windsurf vscode zed gemini gemini-cli opencode"
      flags="--help -h"
      ;;
    "mcp uninstall")
      subs="claude claude-code claude-desktop cursor codex windsurf vscode zed gemini gemini-cli opencode"
      flags="--help -h"
      ;;
    "mcp list")
      subs=""
      flags="--help -h"
      ;;
    "help")
      subs=""
      flags="--help -h"
      ;;
  esac

  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
  elif [ -n "$subs" ]; then
    COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
  fi
}

complete -o default -o bashdefault -F _enconvert enconvert
